### ISSUE TITLE
make styleci happy

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#477]
presently the badge is red

**Comment by GrahamCampbell** [comment]
You can just click the "Create PR" button on the analysis page.

**Comment by cordoval** [comment]
i know but i want a person to review this since it is very long, most of it is good but we also need to tune up the configuration to have it like php_cs, currently is:

```yaml
preset: symfony

enabled:
    - strict_param
    - ordered_use
    - short_array_syntax
    - phpdoc_order
    
disabled:
    - psr0
    #- strict
    
finder:
    path:
        - 'src/'
        - 'tests/'
```
I think the .styleci.yml is too intrusive and well we just need to configure it manually but with a good proper configuration similar to the one we had.
